---
title: "Heart Disease Analysis"
output:
  pdf_document: default
---

# 1. Importing the Data

```{r, Warning = F, messages = F}
# install.packages("ggplot2")
# install.packages("dplyr")
library(ggplot2)
library(dplyr)
hd <- read.csv("heart_2020_cleaned.csv")
# Usually, I check for duplicates. However there is no unique id variable in 
# place, checking for duplicates will only result in false positives.

head(hd$MentalHealth, 40)

n <- c(18:24)
hd2 <- hd[-which(hd$SleepTime %in% n), ]
summary(hd2)
dim(hd2)
```

# 2. Exploring Data Through Visualization

```{r}
hist(hd2$BMI, col = "red", main = "Histogram of BMI")
ggplot(hd2, aes(x = HeartDisease)) +
  geom_bar(aes(y = (..count..)/sum(..count..)), fill = "green") +
  ylab("Proportion (%)") +
  ggtitle("Proportion of People with/without Heart Disease")

hd_sx <- hd2 %>%
  select(Sex, HeartDisease) %>%
  group_by(Sex) %>%
  count(HeartDisease)
ggplot(hd_sx, aes(x = HeartDisease, y = n, fill = Sex)) +
  geom_bar(stat="identity", position = "dodge") +
  xlab("HeartDisease?") +
  ylab("Total") +
  ggtitle("Heart Disease by Sex")

ggplot(hd2, aes(x = HeartDisease, y = BMI, fill = HeartDisease)) + 
  geom_boxplot(fill = c("blue", "red")) +
  ggtitle("Heart Disease Status by BMI")
```

# 3. Creating our Prediction Model.

```{r}
# install.packages("randomforest")
# install.packages("caret")

# First we gotta change the HeartDisease variable into a binary one
# consisting of 1' and 0's so we can use them in modeling.
hd_alt <- hd2 %>% 
  mutate(HeartDisease = ifelse(HeartDisease == 'Yes', 1, 0))

class(hd_alt$HeartDisease)
hd_alt$HeartDisease <- as.factor(hd_alt$HeartDisease) # Changes variable into factor

# Now we finally run a random forest model on the data (as per usual) to see
# if we can somehow obtain a model that can predict heart disease in people.
library(randomForest)
library(caret)
set.seed(5)
s <- createDataPartition(hd_alt$HeartDisease, p = 0.6, list = F)
train <- hd_alt[s, ]
test <- hd_alt[-s, ]

hd_rf <- randomForest(HeartDisease ~ ., train, mtry = 17, 
                       importance = T, na.action = na.omit, ntree = 150)

hd_pred <- predict(hd_rf, test)
varImpPlot(hd_rf)

table_hd <- table("original" = test$HeartDisease, "prediction" = hd_pred)
table_hd
prop.table(table_hd)
acc <- sum(diag(table_hd)) / sum(table_hd)
acc # Calculation of the prediction accuracy.
```